#! /bin/bash

PUB_LOCATION="$HOME/work/tiker.net/webserver/site-codes/tiker.net/files/aufschrieb/"

function dist() {
  cd $1
  echo -n publishing $1... 
  echo -n "[setup]"
  make setup &> /dev/null
  echo -n "[distrib]"
  make all &> /dev/null
  make all &> /dev/null
  make source &> /dev/null
  echo "[copying]"
  cp $1*.pdf $1*-source.tar.gz $PUB_LOCATION
  cd ..
  }

if test $# == 0; then
  dist ana
  dist info
else
  for dir in $*; do 
    dist $dir
    done
  fi

